# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Take_P.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
import cv2


cap = cv2.VideoCapture(0)

def close_Cam():
    print("Close Cam worked")
    cap.release()
    cv2.destroyAllWindows()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Take_Pic = QtWidgets.QPushButton(self.centralwidget)
        self.Take_Pic.setGeometry(QtCore.QRect(320, 430, 130, 60))
        self.Take_Pic.setObjectName("Take_Pic")

        self.Show_Cam = QtWidgets.QPushButton(self.centralwidget)
        self.Show_Cam.setGeometry(QtCore.QRect(320,490,130,60))
        self.Show_Cam.setObjectName("Show_Cam")
        self.Show_Cam.clicked.connect(self.CamF)


        self.Cam_Feed = QtWidgets.QLabel(self.centralwidget)
        self.Cam_Feed.setGeometry(QtCore.QRect(100, 60, 581, 341))
        self.Cam_Feed.setText("")
        self.Cam_Feed.setObjectName("Cam_Feed")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Take_Pic.setText(_translate("MainWindow", "Capture"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.Show_Cam.setText("Show Webcam")

    def CamF(self):
        while (True):
            # Capture frame-by-frame
            ret, frame = cap.read()
            file = 'live.png'
            cv2.imwrite(file, frame)
            if ret is True:
                print("Got Signal")
                self.showCam(frame)
                cv2.waitKey(1)
            else:
                print("Camera not found")
    def showCam(self,frame):
        qformat = QImage.Format_Indexed8

        if len(frame.shape) == 3:
            if(frame.shape[2]) == 4:
                qformat = QImage.Format_RGBA888
            else:
                qformat = QImage.Format_RGB888
        frame = QImage(frame, frame.shape[1],frame.shape[0],qformat)
        frame = frame.rgbSwapped()
        self.Cam_Feed.setPixmap(QPixmap.fromImage(frame))
        self.Cam_Feed.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(close_Cam)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())